TestNG Homework
DaniilLugovsky/AQA27Onl pull request #1
Opened 2024-06-22 14:21 UTC by DaniilLugovsky

2024-07-02 11:04 UTC, wildpioneer requested changes

2024-07-02 11:04 UTC, wildpioneer commented on src/test/java/CalcTest.java
> +    @Test(description = "PositiveTest",testName = "TestPositiveDoble",dependsOnMethods = "testResultIntegers")
Форматирование: у тебя все в одну кучу без пустых строк между тестовыми методами - очень тяжело читать код

2024-07-02 11:04 UTC, wildpioneer commented on src/test/java/CalcTest.java
> +    public void testDataProvider(double a, double b, double result) {
Отсутствуют тесты деления на 0.

2024-07-02 11:04 UTC, wildpioneer commented on src/test/java/CalcTest.java
> +    }
Отсутствуют тесты на Priority, Groups

2024-07-11 14:46 UTC, DaniilLugovsky commented
Исправленная работа

2024-07-15 14:16 UTC, wildpioneer commented
Проверено

2024-07-15 14:16 UTC, closed without merging