Selenide hw
DaniilLugovsky/AQA27Onl pull request #13
Opened 2024-08-19 17:07 UTC by DaniilLugovsky

2024-08-20 10:12 UTC, wildpioneer requested changes

2024-08-20 10:12 UTC, wildpioneer commented on src/test/java/pages/ProductsPage.java
> +        getAddToCartButton().click();
У меня здесь тест падает с exception
Element not found {#add-to-cart-sauce-labs-backpack}

2024-08-20 10:12 UTC, wildpioneer commented on src/test/java/pages/ProductsPage.java
> +
Форматирование по всему документы - сделай красиво

2024-08-20 10:12 UTC, wildpioneer commented on src/test/java/pages/LoginPage.java
> +
Тут не надо 2 пустые строки - достаточно одной

2024-08-20 10:12 UTC, wildpioneer commented on src/test/java/pages/LoginPage.java
> +    public SelenideElement getPasswordInput() {
Между методами надо пустая строка
И вообще воспользуйся  пункт меню Code -> Reformat Code

2024-08-20 19:14 UTC, DaniilLugovsky commented on src/test/java/pages/ProductsPage.java
> +        getAddToCartButton().click();
Перепроверил несколько раз, никаких падений

2024-08-20 19:22 UTC, DaniilLugovsky commented on src/test/java/pages/LoginPage.java
> +    public SelenideElement getPasswordInput() {
Сделал

2024-08-29 06:50 UTC, DaniilLugovsky commented on src/test/java/pages/ProductsPage.java
> +        getAddToCartButton().click();
Окончательно пофиксил проблему

2024-09-10 10:43 UTC, wildpioneer commented
Проверено

2024-09-10 10:43 UTC, closed without merging