Wrappers hm
DaniilLugovsky/AQA27Onl pull request #9
Opened 2024-08-11 13:29 UTC by DaniilLugovsky

2024-08-20 10:21 UTC, wildpioneer requested changes

2024-08-20 10:21 UTC, wildpioneer commented on src/test/java/elements/CheckBox.java
> +        if (!uiElement.isSelected()) {
Реализация правильная - но есть одно 'но'.
Фактически у тебя два метода содержат идентичный код - а следовательно, это дубликаты. Необходимо исправить эту ситуацию.

2024-08-20 10:21 UTC, wildpioneer commented on src/test/java/elements/DropDown.java
> +        parametersElementList.get(index).click();
Все хорошо - есть маленькое замечание. А ты уверен что список развернулся и элемент который ты пытаешся нажать уже clickable?

2024-08-20 10:21 UTC, wildpioneer commented on src/test/java/elements/DropDown.java
> +}
Хочу еще один метод по выбору значения по тексту ;)

2024-08-20 19:02 UTC, DaniilLugovsky commented on src/test/java/elements/CheckBox.java
> +        if (!uiElement.isSelected()) {
Исправил

2024-08-20 19:02 UTC, DaniilLugovsky commented on src/test/java/elements/DropDown.java
> +        parametersElementList.get(index).click();
Вроде исправил)

2024-08-20 19:03 UTC, DaniilLugovsky commented on src/test/java/elements/DropDown.java
> +}
Сделано)

2024-09-10 10:44 UTC, wildpioneer commented
Проверено

2024-09-10 10:44 UTC, closed without merging